#!/bin/bash


case $1 in
          roxterm) if [[ $(pgrep -i $1) ]]; then
                       i3-msg "[class=${1^}] focus"
                   else
                       i3-msg "exec $1"; fi;;
         gpicview) if [[ $(pgrep -i $1) ]]; then
                       i3-msg "[class=${1^}] focus"
                   else
                     i3-msg "exec $1"; fi;;
         qpdfview) if [[ $(pgrep -i $1) ]]; then
                       i3-msg "[class=${1}] focus"
                   else
                       i3-msg "exec $1"; fi;;
         deadbeef) if [[ $(pgrep -i $1) ]]; then
                       i3-msg "[class=${1^}] focus"
                   else
                       i3-msg "exec $1"; fi;;
         smplayer) if [[ $(pgrep -i $1) ]]; then
                       i3-msg "[class=${1}] focus"
                   else
                       i3-msg "exec $1"; fi;;
          firefox) if [[ $(pgrep -i $1) ]]; then
                       i3-msg "[class=${1^}] focus"
                   else
                       i3-msg "exec $1"; fi;;
        doublecmd) if [[ $(pgrep -i $1) ]]; then
                       i3-msg "[class=${1^}] focus"
                   else
                       i3-msg "exec $1"; fi;;
       virtualbox) if [[ $(pgrep -i $1) ]]; then
                       PROCNAME=$(pgrep -li $1 | awk '{print $2}')
                       i3-msg "[class=$PROCNAME] focus"
                   else
                       i3-msg "exec $1"; fi;;
        wireshark) if [[ $(pgrep -i $1) ]]; then
                       i3-msg "[class=${1^}] focus"
                   else
                       i3-msg "exec $1"; fi;;
 transmission-gtk) if [[ $(pgrep -i $1) ]]; then
                      i3-msg "[class=${1^}] focus"
                   else
                      i3-msg "exec $1"; fi;;
esac
